export {default as LoginBg } from "./img/LoginBg.png"
export {default as Logo } from "./img/logo.png"
export {default as Avatar } from "./img/avatar.png"
// export {default as Mango } from "./img/LoginBg.png"
export {default as Delivery } from "./img/delivery.png"
// export {default as HeroBg } from "./img/heroBg.png"
// export {default as Bill } from "./img/LoginBg.png"